version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lezhin-challenge-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:lezhindb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
    networks:
      - lezhin-network
    restart: unless-stopped

  redis:
    image: redis:7.0-alpine
    container_name: lezhin-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - lezhin-network
    restart: unless-stopped
    command: redis-server --appendonly yes

networks:
  lezhin-network:
    driver: bridge

volumes:
  redis-data: