version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5